<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RaghavPC" name="Default test" tests="6" failures="1" timestamp="26 Jul 2017 12:10:35 GMT" time="1.063" errors="0">
  <testcase name="positiveTest" time="0.028" classname="testng.learning.AnnotationAssertionTest"/>
  <testcase name="doLoginTest" time="0.0" classname="testng.learning.AnnotationAssertionTest">
    <skipped/>
  </testcase> <!-- doLoginTest -->
  <testcase name="skipTest" time="0.001" classname="testng.learning.AnnotationAssertionTest">
    <skipped/>
  </testcase> <!-- skipTest -->
  <testcase name="assertTest" time="0.008" classname="testng.learning.AnnotationAssertionTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [expected] but found [actual], 
	error message reported for failure	error message reported for failure">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [expected] but found [actual], 
	error message reported for failure	error message reported for failure
	at org.testng.Assert.fail(Assert.java:94)
	at testng.learning.AnnotationAssertionTest.assertTest(AnnotationAssertionTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- assertTest -->
  <testcase name="changePasswordTest" time="0.0" classname="testng.learning.AnnotationAssertionTest">
    <skipped/>
  </testcase> <!-- changePasswordTest -->
  <testcase name="logoutTest" time="0.0" classname="testng.learning.AnnotationAssertionTest">
    <skipped/>
  </testcase> <!-- logoutTest -->
</testsuite> <!-- Default test -->
