<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="RaghavPC" name="testng.basics.AnnotationAssertionTest" tests="5" failures="1" timestamp="25 Jul 2017 13:57:40 GMT" time="0.135" errors="0">
  <testcase name="doLoginTest" time="0.034" classname="testng.basics.AnnotationAssertionTest">
    <skipped/>
  </testcase> <!-- doLoginTest -->
  <testcase name="changePasswordTest" time="0.000" classname="testng.basics.AnnotationAssertionTest">
    <skipped/>
  </testcase> <!-- changePasswordTest -->
  <testcase name="logoutTest" time="0.000" classname="testng.basics.AnnotationAssertionTest">
    <skipped/>
  </testcase> <!-- logoutTest -->
  <testcase name="skipTest" time="0.002" classname="testng.basics.AnnotationAssertionTest">
    <skipped/>
  </testcase> <!-- skipTest -->
  <testcase name="assertTest" time="0.099" classname="testng.basics.AnnotationAssertionTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [expected] but found [actual],
	error message reported for failure">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [expected] but found [actual],
	error message reported for failure
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testng.basics.AnnotationAssertionTest.assertTest(AnnotationAssertionTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- assertTest -->
</testsuite> <!-- testng.basics.AnnotationAssertionTest -->
